/**
 * FABRE AUTOMATION - Rule Engine Core
 * Release: Rule Engine | Motor de Automação Reativa: Gatilhos -> Condições -> Ações
 * 
 * Central orchestration service:
 * 1. Event Reception & Validation
 * 2. Loop Prevention (rejects sender !== 'contact', metadata.automationId)
 * 3. Idempotency Check (composite key messageId/externalEventId + automationId)
 * 4. Active Automations Loading (channel filtering)
 * 5. Context Resolution (conversation, history, first contact detection)
 * 6. Trigger Evaluation (deterministic matching via TriggerEvaluator)
 * 7. Action Execution (isolated & safe execution via ActionExecutor)
 * 8. Execution Metrics Update & Observability Logging
 */

import { Automation, Conversation, Message } from '../../types';
import { 
  IRuleEngine, 
  RuleEngineEvent, 
  RuleEngineResult, 
  RuleEngineExecutionStatus, 
  EvaluationContext, 
  AutomationExecutionResult 
} from './types';
import { TriggerEvaluator } from './TriggerEvaluator';
import { ActionExecutor } from './ActionExecutor';
import { repositoryManager } from '../repositories';
import { logEngine } from './engineLogger';

export class RuleEngine implements IRuleEngine {
  /**
   * In-memory cache for idempotency tracking
   * Stores composite keys of format: `${identifier}_${automationId}`
   */
  private processedEventKeys = new Set<string>();

  /**
   * Maximum cache size to prevent memory bloat
   */
  private readonly MAX_CACHE_SIZE = 10000;

  /**
   * Clears the idempotency cache (useful for testing and memory maintenance)
   */
  clearIdempotencyCache(): void {
    this.processedEventKeys.clear();
  }

  /**
   * Checks if an event key is in the idempotency cache
   */
  isEventProcessed(eventKey: string): boolean {
    return this.processedEventKeys.has(eventKey);
  }

  /**
   * Helper to build a unique idempotency key
   */
  private buildIdempotencyKey(identifier: string, automationId: string): string {
    return `${identifier}::${automationId}`;
  }

  /**
   * Adds an execution key to the idempotency cache
   */
  private recordExecution(identifier: string, automationId: string): void {
    if (this.processedEventKeys.size >= this.MAX_CACHE_SIZE) {
      // Clear oldest entries (first 1000) when limit is reached
      const iterator = this.processedEventKeys.values();
      for (let i = 0; i < 1000; i++) {
        const next = iterator.next();
        if (next.done) break;
        this.processedEventKeys.delete(next.value);
      }
    }
    this.processedEventKeys.add(this.buildIdempotencyKey(identifier, automationId));
  }

  /**
   * Main entry point: processes a normalized inbound event
   */
  async processEvent(event: RuleEngineEvent): Promise<RuleEngineResult> {
    const timestamp = new Date().toISOString();
    const eventId = event.messageId || event.externalEventId || `evt_${Date.now()}`;

    logEngine('info', 'EVENT_RECEIVED', {
      eventId,
      conversationId: event.conversationId,
      channel: event.channel,
      sender: event.sender,
      contentPreview: event.content ? event.content.slice(0, 40) : '',
    });

    // -------------------------------------------------------------------------
    // 1. VALIDATION: Check mandatory event fields
    // -------------------------------------------------------------------------
    if (!event.conversationId || !event.channel) {
      logEngine('warn', 'INVALID_EVENT', { eventId, event });
      return {
        eventId,
        conversationId: event.conversationId || 'unknown',
        channel: event.channel || 'instagram',
        status: 'INVALID_EVENT',
        reason: 'Evento incompleto: conversationId e channel são obrigatórios.',
        automationsEvaluated: 0,
        matchedAutomations: [],
        timestamp,
      };
    }

    // -------------------------------------------------------------------------
    // 2. LOOP PREVENTION: Outbound / Internal Messages
    // -------------------------------------------------------------------------
    // Messages sent by operator ('user'), bot ('bot'), or system ('system')
    // MUST NEVER trigger automations.
    if (event.sender !== 'contact') {
      logEngine('info', 'LOOP_BLOCKED_SENDER', {
        eventId,
        sender: event.sender,
        reason: 'Mensagem enviada por operador/bot/sistema. Automação ignorada para evitar loops.',
      });

      return {
        eventId,
        conversationId: event.conversationId,
        channel: event.channel,
        status: 'IGNORED_SENDER',
        reason: `Remetente '${event.sender}' não elegível para disparar automações (anti-loop).`,
        automationsEvaluated: 0,
        matchedAutomations: [],
        timestamp,
      };
    }

    // Messages generated by automations (marked with automationId in metadata)
    if (event.metadata?.automationId || event.metadata?.isAutomated === true) {
      logEngine('info', 'LOOP_BLOCKED_AUTOMATION_ORIGIN', {
        eventId,
        automationId: event.metadata?.automationId,
        reason: 'Mensagem originada por automação anterior detectada.',
      });

      return {
        eventId,
        conversationId: event.conversationId,
        channel: event.channel,
        status: 'IGNORED_LOOP',
        reason: 'Mensagem gerada por automação anterior. Descartada para evitar cascata de loops.',
        automationsEvaluated: 0,
        matchedAutomations: [],
        timestamp,
      };
    }

    // -------------------------------------------------------------------------
    // 3. LOAD ACTIVE AUTOMATIONS FOR CHANNEL
    // -------------------------------------------------------------------------
    let allAutomations: Automation[] = [];
    try {
      allAutomations = await repositoryManager.automation.getAutomations();
    } catch (loadErr: unknown) {
      const msg = loadErr instanceof Error ? loadErr.message : String(loadErr);
      logEngine('error', 'LOAD_AUTOMATIONS_ERROR', { error: msg, eventId });
    }

    const activeAutomations = allAutomations.filter(auto => {
      if (!auto.enabled) return false;
      if (auto.channel !== 'all' && auto.channel !== event.channel) return false;
      return true;
    });

    if (activeAutomations.length === 0) {
      logEngine('info', 'NO_ACTIVE_AUTOMATIONS', {
        channel: event.channel,
        totalConfigured: allAutomations.length,
      });

      return {
        eventId,
        conversationId: event.conversationId,
        channel: event.channel,
        status: 'NO_AUTOMATIONS',
        reason: `Nenhuma automação ativa encontrada para o canal '${event.channel}'.`,
        automationsEvaluated: 0,
        matchedAutomations: [],
        timestamp,
      };
    }

    // -------------------------------------------------------------------------
    // 4. LOAD CONVERSATION CONTEXT & HISTORY
    // -------------------------------------------------------------------------
    let conversation: Conversation | null = null;
    let messagesHistory: Message[] = [];

    try {
      conversation = await repositoryManager.conversation.getConversationById(event.conversationId);
      messagesHistory = await repositoryManager.conversation.getMessages(event.conversationId);
    } catch (contextErr) {
      logEngine('warn', 'CONTEXT_RESOLUTION_WARNING', {
        conversationId: event.conversationId,
        error: String(contextErr),
      });
    }

    const contactMessages = messagesHistory.filter(m => m.sender === 'contact');
    const isFirstContact = contactMessages.length <= 1;

    const context: EvaluationContext = {
      conversation,
      messagesHistory,
      isFirstContact,
      depth: 1,
    };

    // -------------------------------------------------------------------------
    // 5. EVALUATE AUTOMATIONS & EXECUTE ACTIONS
    // -------------------------------------------------------------------------
    const matchedResults: AutomationExecutionResult[] = [];
    let hadActionFailure = false;
    let duplicateSkippedCount = 0;

    for (const automation of activeAutomations) {
      const primaryId = event.messageId || event.externalEventId || eventId;
      const keyPrimary = this.buildIdempotencyKey(primaryId, automation.id);
      const keyExternal = event.externalEventId 
        ? this.buildIdempotencyKey(event.externalEventId, automation.id) 
        : null;

      // 5.1 Idempotency Check per automation
      if (this.isEventProcessed(keyPrimary) || (keyExternal && this.isEventProcessed(keyExternal))) {
        logEngine('info', 'IDEMPOTENCY_DUPLICATE_SKIPPED', {
          eventId: primaryId,
          externalEventId: event.externalEventId,
          automationId: automation.id,
        });
        duplicateSkippedCount++;
        continue;
      }

      // 5.2 Trigger Evaluation
      const triggerResult = TriggerEvaluator.evaluate(automation.trigger, event, context);

      if (!triggerResult.matched) {
        logEngine('debug', 'TRIGGER_DID_NOT_MATCH', {
          automationId: automation.id,
          triggerType: automation.trigger.type,
          reason: triggerResult.reason,
        });
        continue;
      }

      logEngine('info', 'TRIGGER_MATCHED', {
        automationId: automation.id,
        automationTitle: automation.title,
        triggerType: automation.trigger.type,
        reason: triggerResult.reason,
      });

      // 5.3 Execute Actions Sequentially
      const actionResults = [];
      let automationSuccess = true;
      let automationError: string | undefined;

      const actions = automation.actions || [];
      for (const action of actions) {
        const res = await ActionExecutor.executeAction(action, automation, event, context);
        actionResults.push(res);

        if (!res.success) {
          automationSuccess = false;
          hadActionFailure = true;
          automationError = res.error;
          logEngine('warn', 'ACTION_EXECUTION_ERROR', {
            actionId: action.id,
            automationId: automation.id,
            error: res.error,
          });
        }
      }

      // 5.4 Record Idempotency
      this.recordExecution(primaryId, automation.id);
      if (event.externalEventId) {
        this.recordExecution(event.externalEventId, automation.id);
      }

      // 5.5 Update Automation Metrics
      try {
        await repositoryManager.automation.updateAutomation(automation.id, {
          executionCount: (automation.executionCount || 0) + 1,
          lastExecutedAt: new Date().toISOString(),
        });
      } catch (metricErr) {
        logEngine('warn', 'METRIC_UPDATE_FAILED', {
          automationId: automation.id,
          error: String(metricErr),
        });
      }

      matchedResults.push({
        automationId: automation.id,
        automationTitle: automation.title,
        triggerMatched: true,
        triggerType: automation.trigger.type,
        matchReason: triggerResult.reason,
        actions: actionResults,
        success: automationSuccess,
        executedAt: new Date().toISOString(),
        error: automationError,
      });
    }

    // -------------------------------------------------------------------------
    // 6. COMPILE FINAL RESULT
    // -------------------------------------------------------------------------
    let finalStatus: RuleEngineExecutionStatus = 'NO_TRIGGER_MATCH';
    let finalReason = 'Nenhum gatilho de automação correspondeu ao evento recebido.';

    if (duplicateSkippedCount > 0 && matchedResults.length === 0) {
      finalStatus = 'IGNORED_DUPLICATE';
      finalReason = 'Evento já processado anteriormente para as automações aplicáveis (idempotência garantida).';
    } else if (matchedResults.length > 0) {
      if (hadActionFailure) {
        finalStatus = 'ACTION_FAILED';
        finalReason = 'Uma ou mais ações apresentaram falhas controladas durante a execução.';
      } else {
        finalStatus = 'TRIGGER_MATCHED';
        finalReason = `${matchedResults.length} automação(ões) correspondida(s) e executada(s) com sucesso.`;
      }
    }

    logEngine('info', 'EXECUTION_COMPLETED', {
      eventId,
      status: finalStatus,
      automationsEvaluated: activeAutomations.length,
      matchedCount: matchedResults.length,
      duplicateSkippedCount,
    });

    return {
      eventId,
      conversationId: event.conversationId,
      channel: event.channel,
      status: finalStatus,
      reason: finalReason,
      automationsEvaluated: activeAutomations.length,
      matchedAutomations: matchedResults,
      timestamp,
    };
  }

  /**
   * Processes a Message object directly
   */
  async processMessage(message: Message, conversation?: Conversation): Promise<RuleEngineResult> {
    const event: RuleEngineEvent = {
      conversationId: message.conversationId,
      channel: message.channel,
      messageId: message.id,
      externalEventId: message.externalEventId,
      sender: message.sender,
      content: message.content,
      contentType: message.contentType,
      timestamp: message.createdAt,
      contact: conversation?.contact ? {
        id: conversation.contact.id,
        name: conversation.contact.name,
        username: conversation.contact.username,
        phone: conversation.contact.phone,
        tags: conversation.contact.tags,
      } : undefined,
      metadata: message.metadata as Record<string, unknown> | undefined,
    };

    return this.processEvent(event);
  }
}

export const ruleEngine = new RuleEngine();
